const source = '// Generated by Swagger-Client.\n\n' +

    "import { queryToUrl, apiHelper } from 'utils';\n\n" +

    '{{#items}}' +
    '{{#if parametersInQuery}}// Query:\n{{#parametersInQuery}}' +
    '// {{name}} -- description: {{description}}, required: {{required}}, type: {{type}}\n' +
    '{{/parametersInQuery}}{{/if}}' +

    '{{#if parametersInBody}}// Body:\n{{#parametersInBody}}' +
    '// {{name}} -- description: {{description}}, required: {{required}}, type: {{type}}\n' +
    '{{/parametersInBody}}{{/if}}' +

    'export const {{apiName}} = ({ ' +
    '{{#parametersInPath}}{{name}}, {{/parametersInPath}}' +
    '{{#if parametersInQuery}}query, {{/if}}' +
    '{{#if parametersInBody}}body, {{/if}}' +
    '...res }) => apiHelper({\n' +
    "    method: '{{method}}',\n" +
    '{{#if parametersInQuery}}' +
    '{{#if parametersInPath}}' +
    '    url: queryToUrl(`{{url}}`, query),\n' +
    '{{else}}' +
    "    url: queryToUrl('{{url}}', query),\n" +
    '{{/if}}' +
    '{{else}}' +
    '{{#if parametersInPath}}' +
    '    url: `{{url}}`,\n' +
    '{{else}}' +
    "    url: '{{url}}',\n" +
    '{{/if}}' +
    '{{/if}}' +
    '{{#if parametersInBody}}' +
    '    body,\n' +
    '{{/if}}' +
    '    ...res,\n' +
    '});\n\n' +
    '{{/items}}';

module.exports = source;